//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hanghoa
    {
        public string mahh { get; set; }
        public string tenhh { get; set; }
        public Nullable<int> slton { get; set; }
        public Nullable<double> gia { get; set; }
    
        public virtual phieunhap phieunhap { get; set; }
        public virtual phieunhap phieunhap1 { get; set; }
        public virtual phieuxuat phieuxuat { get; set; }
        public virtual phieuxuat phieuxuat1 { get; set; }
    }
}
