//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieunhap
    {
        public string manhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string makh { get; set; }
        public string diengiai { get; set; }
        public string mahh { get; set; }
        public Nullable<int> sl { get; set; }
    
        public virtual hanghoa hanghoa { get; set; }
        public virtual hanghoa hanghoa1 { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual khachhang khachhang1 { get; set; }
        public virtual kho kho { get; set; }
        public virtual kho kho1 { get; set; }
    }
}
